{% set name = "buildbot-pkg" %}
{% set version = "2.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7e57a25f44e08bcc2815032305ea9c84688f5f885392ec508febadc8a5194359

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - python >3.5
    - setuptools >=21.2.1
  run:
    - python >3.5
    - setuptools >=21.2.1

test:
  imports:
    - buildbot_pkg

about:
  home: "https://buildbot.net/"
  license: "GNU General Public (GPL)"
  license_family: "LGPL"
  license_file: "LICENSE"
  summary: "Buildbot packaging tools"
  doc_url: "https://docs.buildbot.net"

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
